services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: db_projectComment
    ports:
      - "5432:5432"
    volumes:
      - ./.db-data:/var/lib/postgresql/data